```{r}
#install.packages("matrixcalc")
library("matrixcalc")
```

### A)

```{r}
pi <- c(0.5, 0.5)
A = matrix(c(0.6, 0.1, 0.4, 0.9), nrow = 2)

A
```

```{r}
t(A) %*% pi
```

```{r}
t(matrix.power(A, 2)) %*% pi
```

```{r}
t(matrix.power(A, 3)) %*% pi
```

```{r}
B <- matrix(c(1/6, 1/10, 1/6, 1/10, 1/6, 1/10, 1/6, 1/10, 1/6, 1/10, 1/6, 1/2),
            nrow = 2)
B
```

```{r}
t(B) %*% t(matrix.power(A, 1)) %*% pi
```

```{r}
t(B) %*% t(matrix.power(A, 2)) %*% pi
```

```{r}
t(B) %*% t(matrix.power(A, 3)) %*% pi
```

### B)

```{r}
#install.packages("HMM")
library(HMM)

model.HMM <- initHMM(c("fair", "loaded"),
                  c("1","2", "3", "4", "5", "6"),
                  startProbs = pi,
                  transProbs = A,
                  emissionProbs = B)
summary(model.HMM)
```
```{r}
sim1 <- simHMM(model.HMM, 100)
sim2 <- simHMM(model.HMM, 100)
sim3 <- simHMM(model.HMM, 100)
sim1
```

### C)
 
```{r}
(1/6^20 )/(1/6^20 + 1/10 ^ 7 * 1/2 * 1/10 * 1/2^2 * 1/10 * 1/2^2 * 1/10^6)
```
```{r}
(1/10 ^ 7 * 1/2 * 1/10 * 1/2^2 * 1/10 * 1/2^2 * 1/10^6) /(1/6^20 + 1/10 ^ 7 * 1/2 * 1/10 * 1/2^2 * 1/10 * 1/2^2 * 1/10^6)
```

